name: my_farm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.0.0
  go_router: ^14.1.1
  google_fonts: ^6.2.1
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
